apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-app-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jinagamvasubabu/argo-cd-demo-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-demo-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
