apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  selector:
    matchLabels:
      app: argocd-demo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: argocd-demo-app
        image: hangoutdude/argocd-demo-app:1.0.1
        ports:
        - containerPort: 3000
